### PR TITLE
please review for Article 7 : Code Components : Activities

### PR DESCRIPTION
**Pull request by thisrahul**
## Issue Fixed

Issue Number https://github.com/utkarsh006/Eazy-Android/issues/23

## Changes Proposed

1.Create a new file in the Articles folder by the name Articles/Article 7 : Code Components : Activities.md
2.I have written an article which talks about the activity and activity lifecycle

## Check List ( Tick all the applicable boxes )

- [x] My Code follows the code style of this project.
- [x] The title of My PR is a short description of the requested changes.
- [x] Artticle/Blog added in Article Folder.
- [x] I have starred this repo.

## Note to Reviewers 

( If you want to write additional points for the maintainer note them down here )

Thanks to give me opportunity to write an article on activity lifecycle

## Upload Output Screenshots/Gif

Screenshot (4)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@thisrahul Complete the PR Template.

**Comment by thisrahul** [comment]
updated**

**Comment by utkarsh006** [comment]
@thisrahul Tick mark the checkboxes and show the output of your readme rather than the code.

**Comment by thisrahul** [comment]
please check if is there any more changes require or not.

**Pull request merged**
