### PR TITLE
Added article related to layout and its types

### PR DESCRIPTION
**Pull request by apoorva1823000**
## Issue Fixed

Issue Number  #25

## Changes Proposed

Wrote article about Layout and its types in easy to comprehend and understand language as well as termenologies

### Image demosnstration for newbies

<div align="center">
  
  You have to put `x` inside this `[]`
  
  
  
  Preview
  
  
  
</div>  

- [x] My Code follows the code style of this project.
- [x] The title of My PR is a short description of the requested changes.
- [x] I have stared this repo.

## Note to Reviewers 

( If you want to write additional points for maintainer note down here )

I am an android development learner and hence open to more contributions over this project,

## Upload Output Screenshots/Gif
Screenshot 2022-10-01 114113

### CODE REVIEW

**Comment by utkarsh006** [comment]
@apoorva1823000 Nicely done. Highlight the important keywords (bold) and write some lines in points using (-)

**Comment by apoorva1823000** [comment]
@utkarsh006 so should I make changes and submit again ?

**Comment by utkarsh006** [comment]
@apoorva1823000 Yes buddy. Just make changes in the readme file in your branch. Also, do make sure that you have explained the concepts in your own words.

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
