### PR TITLE
Android Project Structure Added

### PR DESCRIPTION
**Pull request by HawkItzme**
## Issue Fixed

Issue Number #19 

## Changes Proposed

Write here what changes you did
Added Article on Android Project Structure

## Check List ( Tick all the applicable boxes )

- [x] My Code follows the code style of this project.
- [x] The title of My PR is a short description of the requested changes.
- [x] Article/Blog added in Article Folder.
- [x] I have starred this repo.

## Note to Reviewers 

( If you want to write additional points for the maintainer note them down here )

### CODE REVIEW

**Comment by HawkItzme** [comment]
Please review and merge @utkarsh006

**Comment by utkarsh006** [comment]
@HawkItzme Attach the screenshot of how your README file is looking.

**Comment by HawkItzme** [comment]
Readme 1
Readme 2
Readme 3


@utkarsh006 please review

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
